version: '3.8'

services:
  googlemaps-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: googlemaps-scraper
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS=--workers=3 --timeout=300 --max-requests=50 --max-requests-jitter=10
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 3G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/fetch-reviews?place_id=ChIJ_5LxRO2ZoRQRE1Q7-KhVZpM"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 